package view;

/**
 *
 * @author Scalco
 */
public class CadastrarSala extends javax.swing.JFrame {

    private static CadastrarSala unicCadastrarSala;

    private CadastrarSala() {
        initComponents();
    }

    public static CadastrarSala geraCadastrarSala() {
        if (unicCadastrarSala == null) {
            unicCadastrarSala = new CadastrarSala();
        }

        return unicCadastrarSala;
    }

    public void abrirTela() {
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        largura_input = new javax.swing.JTextField();
        assento_botao_b_4 = new javax.swing.JButton();
        assento_botao_b_5 = new javax.swing.JButton();
        assento_botao_a_1 = new javax.swing.JButton();
        assento_botao_b_6 = new javax.swing.JButton();
        assento_botao_a_2 = new javax.swing.JButton();
        assento_botao_a_3 = new javax.swing.JButton();
        assento_botao_a_4 = new javax.swing.JButton();
        assento_botao_a_5 = new javax.swing.JButton();
        assento_botao_a_6 = new javax.swing.JButton();
        assento_botao_b_1 = new javax.swing.JButton();
        filme_label = new javax.swing.JLabel();
        assento_botao_b_2 = new javax.swing.JButton();
        assento_botao_b_3 = new javax.swing.JButton();
        profundidade_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cadastrar_botao = new javax.swing.JButton();
        voltar_botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Sala");

        jLabel2.setText("Nome da sala");

        jTextField1.setToolTipText("Nome da sala");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("X");

        largura_input.setToolTipText("Largura");
        largura_input.setAutoscrolls(false);
        largura_input.setInheritsPopupMenu(true);

        assento_botao_b_4.setIconTextGap(0);
        assento_botao_b_4.setLabel("B3");
        assento_botao_b_4.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_b_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_b_4ActionPerformed(evt);
            }
        });

        assento_botao_b_5.setIconTextGap(0);
        assento_botao_b_5.setLabel("B4");
        assento_botao_b_5.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_b_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_b_5ActionPerformed(evt);
            }
        });

        assento_botao_a_1.setText("A1");
        assento_botao_a_1.setIconTextGap(0);
        assento_botao_a_1.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_a_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_a_1ActionPerformed(evt);
            }
        });

        assento_botao_b_6.setIconTextGap(0);
        assento_botao_b_6.setLabel("B5");
        assento_botao_b_6.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_b_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_b_6ActionPerformed(evt);
            }
        });

        assento_botao_a_2.setIconTextGap(0);
        assento_botao_a_2.setLabel("A2");
        assento_botao_a_2.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_a_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_a_2ActionPerformed(evt);
            }
        });

        assento_botao_a_3.setIconTextGap(0);
        assento_botao_a_3.setLabel("A3");
        assento_botao_a_3.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_a_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_a_3ActionPerformed(evt);
            }
        });

        assento_botao_a_4.setIconTextGap(0);
        assento_botao_a_4.setLabel("A4");
        assento_botao_a_4.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_a_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_a_4ActionPerformed(evt);
            }
        });

        assento_botao_a_5.setIconTextGap(0);
        assento_botao_a_5.setLabel("A5");
        assento_botao_a_5.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_a_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_a_5ActionPerformed(evt);
            }
        });

        assento_botao_a_6.setIconTextGap(0);
        assento_botao_a_6.setLabel("A6");
        assento_botao_a_6.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_a_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_a_6ActionPerformed(evt);
            }
        });

        assento_botao_b_1.setIconTextGap(0);
        assento_botao_b_1.setLabel("B6");
        assento_botao_b_1.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_b_1ActionPerformed(evt);
            }
        });

        filme_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        filme_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filme_label.setText("Filme");

        assento_botao_b_2.setIconTextGap(0);
        assento_botao_b_2.setLabel("B1");
        assento_botao_b_2.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_b_2ActionPerformed(evt);
            }
        });

        assento_botao_b_3.setIconTextGap(0);
        assento_botao_b_3.setLabel("B2");
        assento_botao_b_3.setMargin(new java.awt.Insets(3, 5, 3, 5));
        assento_botao_b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento_botao_b_3ActionPerformed(evt);
            }
        });

        profundidade_input.setToolTipText("Profundidade");

        jLabel4.setText("Dimensões");

        cadastrar_botao.setText("Cadastrar");

        voltar_botao.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(largura_input, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profundidade_input, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assento_botao_b_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_b_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_b_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_b_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_b_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_b_1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assento_botao_a_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_a_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_a_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_a_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_a_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assento_botao_a_6))
                            .addComponent(filme_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltar_botao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assento_botao_b_2)
                            .addComponent(assento_botao_b_3)
                            .addComponent(assento_botao_b_4)
                            .addComponent(assento_botao_b_5)
                            .addComponent(assento_botao_b_6)
                            .addComponent(assento_botao_b_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assento_botao_a_1)
                            .addComponent(assento_botao_a_2)
                            .addComponent(assento_botao_a_3)
                            .addComponent(assento_botao_a_4)
                            .addComponent(assento_botao_a_5)
                            .addComponent(assento_botao_a_6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(largura_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(profundidade_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(filme_label)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltar_botao)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assento_botao_b_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_b_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_b_4ActionPerformed

    private void assento_botao_b_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_b_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_b_5ActionPerformed

    private void assento_botao_a_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_a_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_a_1ActionPerformed

    private void assento_botao_b_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_b_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_b_6ActionPerformed

    private void assento_botao_a_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_a_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_a_2ActionPerformed

    private void assento_botao_a_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_a_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_a_3ActionPerformed

    private void assento_botao_a_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_a_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_a_4ActionPerformed

    private void assento_botao_a_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_a_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_a_5ActionPerformed

    private void assento_botao_a_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_a_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_a_6ActionPerformed

    private void assento_botao_b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_b_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_b_1ActionPerformed

    private void assento_botao_b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_b_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_b_2ActionPerformed

    private void assento_botao_b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento_botao_b_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assento_botao_b_3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assento_botao_a_1;
    private javax.swing.JButton assento_botao_a_2;
    private javax.swing.JButton assento_botao_a_3;
    private javax.swing.JButton assento_botao_a_4;
    private javax.swing.JButton assento_botao_a_5;
    private javax.swing.JButton assento_botao_a_6;
    private javax.swing.JButton assento_botao_b_1;
    private javax.swing.JButton assento_botao_b_2;
    private javax.swing.JButton assento_botao_b_3;
    private javax.swing.JButton assento_botao_b_4;
    private javax.swing.JButton assento_botao_b_5;
    private javax.swing.JButton assento_botao_b_6;
    private javax.swing.JButton cadastrar_botao;
    private javax.swing.JLabel filme_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField largura_input;
    private javax.swing.JTextField profundidade_input;
    private javax.swing.JButton voltar_botao;
    // End of variables declaration//GEN-END:variables
}
