package view;

import controller.SessaoControl;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.dao.DaoFactory;
import model.dao.FilmeDao;
import model.dao.SalaDao;
import model.entities.Filme;
import model.entities.Sala;
import model.entities.Usuario;

/**
 *
 * @author Scalco
 */
public class TelaCadastrarSessao extends javax.swing.JFrame {

    private static TelaCadastrarSessao unicCadastrarSessao;
    private Usuario usuario;

    private List<Filme> filmes;
    private List<Sala> salas;

    private TelaCadastrarSessao(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    public static TelaCadastrarSessao geraCadastrarSessao(Usuario usuario) {
        if (unicCadastrarSessao == null) {
            unicCadastrarSessao = new TelaCadastrarSessao(usuario);
        }

        return unicCadastrarSessao;
    }

    public void abrirTela() {
        listarFilmes();
        listarSalas();
        renderizaTela();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linguagem_grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filme_combo_box = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sala_combo_box = new javax.swing.JComboBox<>();
        cadastrar_botao = new javax.swing.JButton();
        voltar_botao = new javax.swing.JButton();
        dublado_radio = new javax.swing.JRadioButton();
        legendado_radio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        data_input = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hora_input = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Sessao");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Sessão");

        jLabel2.setText("Selecione o Filme");

        filme_combo_box.setToolTipText("Filmes disponíveis");
        filme_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filme_combo_boxActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione a Sala");

        sala_combo_box.setToolTipText("Filmes disponíveis");

        cadastrar_botao.setText("Cadastrar");
        cadastrar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_botaoActionPerformed(evt);
            }
        });

        voltar_botao.setText("Voltar");
        voltar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_botaoActionPerformed(evt);
            }
        });

        linguagem_grupo.add(dublado_radio);
        dublado_radio.setSelected(true);
        dublado_radio.setText("Dublado");
        dublado_radio.setToolTipText("Dublado");
        dublado_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dublado_radioActionPerformed(evt);
            }
        });

        linguagem_grupo.add(legendado_radio);
        legendado_radio.setText("Legendado");
        legendado_radio.setToolTipText("Legendado");
        legendado_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legendado_radioActionPerformed(evt);
            }
        });

        jLabel4.setText("Idioma");

        data_input.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        data_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_inputActionPerformed(evt);
            }
        });

        jLabel5.setText("Data (dd/MM/aaaa)");

        jLabel6.setText("Horário (HH:mm)");

        hora_input.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar_botao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(sala_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filme_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dublado_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(legendado_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(data_input, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hora_input, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 411, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filme_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sala_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dublado_radio)
                    .addComponent(legendado_radio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar_botao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_botaoActionPerformed
        voltar();
    }//GEN-LAST:event_voltar_botaoActionPerformed

    private void filme_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filme_combo_boxActionPerformed

    }//GEN-LAST:event_filme_combo_boxActionPerformed

    private void dublado_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dublado_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dublado_radioActionPerformed

    private void legendado_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legendado_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legendado_radioActionPerformed

    private void cadastrar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_botaoActionPerformed
        cadastrarSessao();
    }//GEN-LAST:event_cadastrar_botaoActionPerformed

    private void data_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_inputActionPerformed

    private void voltar() {
        dispose();
        limparTela();
        TelaGerenciarSessao.geraTelaGerenciarSessao(usuario).abrirTela();
    }

    private void renderizaTela() {
        ArrayList<String> filmeStrList = new ArrayList<>();
        ArrayList<String> salaStrList = new ArrayList<>();

        for (Filme filme : filmes) {
            filmeStrList.add(filme.getNome());
        }

        for (Sala sala : salas) {
            salaStrList.add(sala.getNome());
        }

        filme_combo_box.setModel(new javax.swing.DefaultComboBoxModel(filmeStrList.toArray()));
        sala_combo_box.setModel(new javax.swing.DefaultComboBoxModel(salaStrList.toArray()));
    }

    private String getIdioma() {
        if (dublado_radio.isSelected()) {
            return "Dublado";
        } else if (legendado_radio.isSelected()) {
            return "Legendado";
        }
        return "Não selecionado";
    }

    private void limparTela() {
        filme_combo_box.removeAll();
        filme_combo_box.setSelectedIndex(-1);
        sala_combo_box.removeAll();
        sala_combo_box.setSelectedIndex(-1);
        dublado_radio.setSelected(true);
        data_input.setText("");
        hora_input.setText("");
    }

    private void cadastrarSessao() {
        String idioma = getIdioma();
        String strData = data_input.getText() + " " + hora_input.getText();
        Filme filme = filmes.get(filme_combo_box.getSelectedIndex());
        Sala sala = salas.get(sala_combo_box.getSelectedIndex());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime data = LocalDateTime.parse(strData, formatter);

        try {
            SessaoControl sessao = new SessaoControl();
            boolean sucesso = sessao.cadastrarSessao(idioma, data, filme, sala);
            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                voltar();
            } else {
                JOptionPane.showMessageDialog(null, "Erro no preenchimento de campos!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }

    private void listarFilmes() {
        FilmeDao filmeDao = DaoFactory.createFilmeDao();
        filmes = filmeDao.findByAll();
    }

    private void listarSalas() {
        SalaDao salaDao = DaoFactory.createSalaDao();
        salas = salaDao.findByAll();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_botao;
    private javax.swing.JFormattedTextField data_input;
    private javax.swing.JRadioButton dublado_radio;
    private javax.swing.JComboBox<String> filme_combo_box;
    private javax.swing.JFormattedTextField hora_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton legendado_radio;
    private javax.swing.ButtonGroup linguagem_grupo;
    private javax.swing.JComboBox<String> sala_combo_box;
    private javax.swing.JButton voltar_botao;
    // End of variables declaration//GEN-END:variables
}
