package view;

import java.awt.Dimension;
import java.awt.Image;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Base64;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.dao.DaoFactory;
import model.dao.SessaoDao;
import model.entities.Filme;
import model.entities.Sessao;

/**
 *
 * @author Scalco
 */
public class TelaFilme extends javax.swing.JFrame {

    private static TelaFilme unicFilme;
    private Filme filme;

    private List<Sessao> sessoes;

    private TelaFilme() {
        initComponents();
    }

    public static TelaFilme geraFilme() {
        if (unicFilme == null) {
            unicFilme = new TelaFilme();
        }

        return unicFilme;
    }

    public void abrirTela(Filme filme) {
        this.filme = filme;
        buscaSessoes();
        renderizaTela();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filme_nome = new javax.swing.JLabel();
        voltar_botao = new javax.swing.JButton();
        idade_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_text = new javax.swing.JTextArea();
        filme_img = new javax.swing.JLabel();
        sessoes_pnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filme");

        filme_nome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filme_nome.setText("Homem Aranha - vamos para Casa? ");

        voltar_botao.setText("Voltar");
        voltar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_botaoActionPerformed(evt);
            }
        });

        idade_text.setText("12+");

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setBorder(null);

        descricao_text.setEditable(false);
        descricao_text.setColumns(20);
        descricao_text.setLineWrap(true);
        descricao_text.setRows(5);
        descricao_text.setText("Homem Aranha vai para casa, brincar com a Mary Jane, e nesse filme ele te convida para ir para a casa com ele, em um filme cheio de suspence, drama e muita comédia, você descobrirá tudo que o homem aranha fará com você, dentro da sua casa, você está preparado, para as traquinagens aranhas?");
        descricao_text.setWrapStyleWord(true);
        descricao_text.setAutoscrolls(false);
        descricao_text.setBorder(null);
        jScrollPane1.setViewportView(descricao_text);

        javax.swing.GroupLayout sessoes_pnlLayout = new javax.swing.GroupLayout(sessoes_pnl);
        sessoes_pnl.setLayout(sessoes_pnlLayout);
        sessoes_pnlLayout.setHorizontalGroup(
            sessoes_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sessoes_pnlLayout.setVerticalGroup(
            sessoes_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessoes_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filme_img, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(filme_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                    .addComponent(idade_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)))
                            .addComponent(voltar_botao))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar_botao)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filme_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idade_text)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(filme_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sessoes_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_botaoActionPerformed
        voltar();
    }//GEN-LAST:event_voltar_botaoActionPerformed

    private void buscaSessoes() {
        try {
            SessaoDao sessaoDao = DaoFactory.createSessaoDao();
            sessoes = sessaoDao.buscarSessaoDisponivel(filme.getId());
        } catch (SQLException ecp) {
        }
    }

    private void renderizaTela() {
        filme_nome.setText(filme.getNome());
        idade_text.setText(filme.getClassificacao());
        descricao_text.setText(filme.getDescricao());

        try {
            byte[] bytes = Base64.getDecoder().decode(filme.getBase64Image());
            ImageIcon imageIcon = new ImageIcon(bytes);
            Image image = imageIcon.getImage();
            Image newimg = image.getScaledInstance(168, 224, java.awt.Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(newimg);
            filme_img.setIcon(imageIcon);
        } catch (Exception exc) {
            filme_img.setText("Erro");
        }

        int x = 10;
        int y = 10;
        int width = 100;
        int height = 35;

        for (int i = 1; i <= sessoes.size(); i++) {
            Sessao sessao = sessoes.get(i-1);
            JButton button = new JButton();
            LocalDateTime hora = sessao.getHorarioDaSessao();

            button.setText(hora.format(DateTimeFormatter.ofPattern("dd/MM - HH:mm")));
            button.addActionListener((java.awt.event.ActionEvent evt) -> {
                irParaAssento(sessao);
            });

            button.setBounds(x, y, width, height);
            sessoes_pnl.add(button);

            x = x + width + 20;
            if (i % 4 == 0) {
                x = 10;
                y = y + height + 15;
            }
        }

        sessoes_pnl.setPreferredSize(new Dimension(660, 175));
        sessoes_pnl.revalidate();
        sessoes_pnl.repaint();
    }

    private void voltar() {
        dispose();
        TelaCatalogoDeFilmes.geraCatalogoDeFilmes().abrirTela();
    }

    private void irParaAssento(Sessao sessao) {
        dispose();
        TelaEscolherAssento.geraEscolherAssento().abrirTela(sessao);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricao_text;
    private javax.swing.JLabel filme_img;
    private javax.swing.JLabel filme_nome;
    private javax.swing.JLabel idade_text;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sessoes_pnl;
    private javax.swing.JButton voltar_botao;
    // End of variables declaration//GEN-END:variables
}
