package view;

/**
 *
 * @author Scalco
 */
public class TelaCentralAdministrador extends javax.swing.JFrame {

    private static TelaCentralAdministrador unicTelaCentralAdministrador;

    private TelaCentralAdministrador() {
        initComponents();
    }

    public static TelaCentralAdministrador geraTelaCentralAdministrador() {
        if (unicTelaCentralAdministrador == null) {
            unicTelaCentralAdministrador = new TelaCentralAdministrador();
        }

        return unicTelaCentralAdministrador;
    }

    public void abrirTela() {
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadastrar_botao = new javax.swing.JButton();
        gerenciar_salas_botao = new javax.swing.JButton();
        gerenciar_sessoes_botao = new javax.swing.JButton();
        gerenciar_filmes_botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(678, 443));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Makes Cinema Easier");

        cadastrar_botao.setText("Cadastrar Usuários");
        cadastrar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_botaoActionPerformed(evt);
            }
        });

        gerenciar_salas_botao.setText("Gerenciar Salas");
        gerenciar_salas_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_salas_botaoActionPerformed(evt);
            }
        });

        gerenciar_sessoes_botao.setText("Gerenciar Sessões");
        gerenciar_sessoes_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_sessoes_botaoActionPerformed(evt);
            }
        });

        gerenciar_filmes_botao.setText("Gerenciar Filmes");
        gerenciar_filmes_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_filmes_botaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerenciar_filmes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerenciar_sessoes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerenciar_salas_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciar_salas_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciar_sessoes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciar_filmes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_botaoActionPerformed
        irParaCadastro();
    }//GEN-LAST:event_cadastrar_botaoActionPerformed

    private void gerenciar_salas_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_salas_botaoActionPerformed
        irParaGerenciarSala();
    }//GEN-LAST:event_gerenciar_salas_botaoActionPerformed

    private void gerenciar_sessoes_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_sessoes_botaoActionPerformed
        irParaGerenciarSessao();
    }//GEN-LAST:event_gerenciar_sessoes_botaoActionPerformed

    private void gerenciar_filmes_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_filmes_botaoActionPerformed
        irParaGerenciarFilme();
    }//GEN-LAST:event_gerenciar_filmes_botaoActionPerformed

    public void irParaCadastro() {
        dispose();
        TelaCadastrarUsuario.geraCadastrarUsuario().abrirTela();
    }

    public void irParaGerenciarSessao() {
        dispose();
        TelaGerenciarSessao.geraTelaGerenciarSessao().abrirTela();
    }

    public void irParaGerenciarFilme() {
        dispose();
        TelaGerenciarFilme.geraTelaGerenciarFilme().abrirTela();
    }

    public void irParaGerenciarSala() {
        dispose();
        TelaGerenciarSala.geraTelaGerenciarSala().abrirTela();
    }
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCatalogoDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCatalogoDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCatalogoDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCatalogoDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCentralAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_botao;
    private javax.swing.JButton gerenciar_filmes_botao;
    private javax.swing.JButton gerenciar_salas_botao;
    private javax.swing.JButton gerenciar_sessoes_botao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
