package view;

import model.entities.Usuario;

/**
 *
 * @author Scalco
 */
public class TelaCentralAdministrador extends javax.swing.JFrame {

    private static TelaCentralAdministrador unicTelaCentralAdministrador;
    private Usuario usuario;

    private TelaCentralAdministrador(){
        initComponents();
    }

    public static TelaCentralAdministrador geraTelaCentralAdministrador() {
        if (unicTelaCentralAdministrador == null) {
            unicTelaCentralAdministrador = new TelaCentralAdministrador();
            
        }

        return unicTelaCentralAdministrador;
    }

    public void abrirTela(Usuario usuario) {
        this.usuario = usuario;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadastrar_botao = new javax.swing.JButton();
        gerenciar_salas_botao = new javax.swing.JButton();
        gerenciar_sessoes_botao = new javax.swing.JButton();
        gerenciar_filmes_botao = new javax.swing.JButton();
        eidtar_perfil_botao = new javax.swing.JButton();
        sair_botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setPreferredSize(new java.awt.Dimension(678, 443));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Makes Cinema Easier");

        cadastrar_botao.setText("Cadastrar Usuários");
        cadastrar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_botaoActionPerformed(evt);
            }
        });

        gerenciar_salas_botao.setText("Gerenciar Salas");
        gerenciar_salas_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_salas_botaoActionPerformed(evt);
            }
        });

        gerenciar_sessoes_botao.setText("Gerenciar Sessões");
        gerenciar_sessoes_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_sessoes_botaoActionPerformed(evt);
            }
        });

        gerenciar_filmes_botao.setText("Gerenciar Filmes");
        gerenciar_filmes_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_filmes_botaoActionPerformed(evt);
            }
        });

        eidtar_perfil_botao.setText("Editar conta");
        eidtar_perfil_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidtar_perfil_botaoActionPerformed(evt);
            }
        });

        sair_botao.setText("sair");
        sair_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_botaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerenciar_filmes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerenciar_sessoes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerenciar_salas_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sair_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eidtar_perfil_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eidtar_perfil_botao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair_botao)
                .addGap(43, 43, 43)
                .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciar_salas_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciar_sessoes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciar_filmes_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_botaoActionPerformed
        irParaCadastro();
    }//GEN-LAST:event_cadastrar_botaoActionPerformed

    private void gerenciar_salas_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_salas_botaoActionPerformed
        irParaGerenciarSala();
    }//GEN-LAST:event_gerenciar_salas_botaoActionPerformed

    private void gerenciar_sessoes_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_sessoes_botaoActionPerformed
        irParaGerenciarSessao();
    }//GEN-LAST:event_gerenciar_sessoes_botaoActionPerformed

    private void gerenciar_filmes_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_filmes_botaoActionPerformed
        irParaGerenciarFilme();
    }//GEN-LAST:event_gerenciar_filmes_botaoActionPerformed

    private void sair_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_botaoActionPerformed
        sair();
    }//GEN-LAST:event_sair_botaoActionPerformed

    private void eidtar_perfil_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidtar_perfil_botaoActionPerformed
        editar();
    }//GEN-LAST:event_eidtar_perfil_botaoActionPerformed

    private void editar(){
        dispose();
        TelaAtualizarUsuario.geraTelaAtualizarUsuario().abrirTela(usuario);
    }
    
    private void sair(){
        dispose();
        TelaCatalogoDeFilmes.geraCatalogoDeFilmes().abrirTela();
    }
    
    private void irParaCadastro() {
        dispose();
        TelaCadastrarUsuario.geraCadastrarUsuario().abrirTela(usuario);
    }

    private void irParaGerenciarSessao() {
        dispose();
        TelaGerenciarSessao.geraTelaGerenciarSessao().abrirTela(usuario);
    }

    private void irParaGerenciarFilme() {
        dispose();
        TelaGerenciarFilme.geraTelaGerenciarFilme().abrirTela(usuario);
    }

    private void irParaGerenciarSala() {
        dispose();
        TelaGerenciarSala.geraTelaGerenciarSala().abrirTela(usuario);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_botao;
    private javax.swing.JButton eidtar_perfil_botao;
    private javax.swing.JButton gerenciar_filmes_botao;
    private javax.swing.JButton gerenciar_salas_botao;
    private javax.swing.JButton gerenciar_sessoes_botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sair_botao;
    // End of variables declaration//GEN-END:variables
}
