package view;

import controller.FilmeControl;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.entities.Usuario;

/**
 *
 * @author Scalco
 */
public class TelaCadastrarFilme extends javax.swing.JFrame {

    private static TelaCadastrarFilme unicCadastrarFilme;
    private String imagemBase64;
    private Usuario usuario;

    private TelaCadastrarFilme() {
        initComponents();
    }

    public static TelaCadastrarFilme geraCadastrarFilme() {
        if (unicCadastrarFilme == null) {
            unicCadastrarFilme = new TelaCadastrarFilme();
        }

        return unicCadastrarFilme;
    }

    public void abrirTela(Usuario usuario) {
        this.usuario = usuario;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idade_grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filme_input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_input = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cadastrar_botao = new javax.swing.JButton();
        voltar_botao = new javax.swing.JButton();
        dez_radio = new javax.swing.JRadioButton();
        livre_radio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        doze_radio = new javax.swing.JRadioButton();
        quatorze_radio = new javax.swing.JRadioButton();
        dezesseis_radio = new javax.swing.JRadioButton();
        dezoito_radio = new javax.swing.JRadioButton();
        image_action = new javax.swing.JButton();
        image_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        duracao_text = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Filme");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Filme");

        jLabel2.setText("Nome do filme");

        filme_input.setToolTipText("Nome do filme");

        descricao_input.setColumns(20);
        descricao_input.setRows(5);
        jScrollPane1.setViewportView(descricao_input);

        jLabel3.setText("Descrição");

        cadastrar_botao.setText("Cadastrar");
        cadastrar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_botaoActionPerformed(evt);
            }
        });

        voltar_botao.setText("Voltar");
        voltar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_botaoActionPerformed(evt);
            }
        });

        idade_grupo.add(dez_radio);
        dez_radio.setText("10+");
        dez_radio.setToolTipText("10+");
        dez_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dez_radioActionPerformed(evt);
            }
        });

        idade_grupo.add(livre_radio);
        livre_radio.setSelected(true);
        livre_radio.setText("Livre");
        livre_radio.setToolTipText("Livre");
        livre_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livre_radioActionPerformed(evt);
            }
        });

        jLabel5.setText("Classificação indicativa");

        idade_grupo.add(doze_radio);
        doze_radio.setText("12+");
        doze_radio.setToolTipText("12+");
        doze_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doze_radioActionPerformed(evt);
            }
        });

        idade_grupo.add(quatorze_radio);
        quatorze_radio.setText("14+");
        quatorze_radio.setToolTipText("14+");
        quatorze_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatorze_radioActionPerformed(evt);
            }
        });

        idade_grupo.add(dezesseis_radio);
        dezesseis_radio.setText("16+");
        dezesseis_radio.setToolTipText("16+");
        dezesseis_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dezesseis_radioActionPerformed(evt);
            }
        });

        idade_grupo.add(dezoito_radio);
        dezoito_radio.setText("18+");
        dezoito_radio.setToolTipText("18+");
        dezoito_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dezoito_radioActionPerformed(evt);
            }
        });

        image_action.setText("Subir imagem");
        image_action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_actionActionPerformed(evt);
            }
        });

        image_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Duração");

        duracao_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setText("Minutos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar_botao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(64, 455, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(livre_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dez_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doze_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quatorze_radio)
                                .addGap(12, 12, 12)
                                .addComponent(dezesseis_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dezoito_radio)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1)
                                .addComponent(filme_input, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(duracao_text, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(image_action, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filme_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duracao_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(image_action)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livre_radio)
                    .addComponent(dez_radio)
                    .addComponent(doze_radio)
                    .addComponent(quatorze_radio)
                    .addComponent(dezesseis_radio)
                    .addComponent(dezoito_radio))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar_botao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dez_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dez_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dez_radioActionPerformed

    private void livre_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livre_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livre_radioActionPerformed

    private void doze_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doze_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doze_radioActionPerformed

    private void quatorze_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatorze_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quatorze_radioActionPerformed

    private void dezesseis_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dezesseis_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dezesseis_radioActionPerformed

    private void dezoito_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dezoito_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dezoito_radioActionPerformed

    private void image_actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_actionActionPerformed
        Icon icon = image_label.getIcon();
        if (icon == null) {
            uploadImage();
        } else {
            resetImage();
        }
    }//GEN-LAST:event_image_actionActionPerformed

    private void cadastrar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_botaoActionPerformed
        criarFilme();
    }//GEN-LAST:event_cadastrar_botaoActionPerformed

    private void voltar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_botaoActionPerformed
        voltar();
    }//GEN-LAST:event_voltar_botaoActionPerformed

    private void voltar() {
        dispose();
        limparTela();
        TelaGerenciarFilme.geraTelaGerenciarFilme().abrirTela(usuario);
    }

    private void limparTela() {
        filme_input.setText("");
        descricao_input.setText("");
        livre_radio.setSelected(true);
        duracao_text.setText("");
        resetImage();
    }

    private String getClassificacao() {
        if (livre_radio.isSelected()) {
            return "Livre";
        } else if (dez_radio.isSelected()) {
            return "10+";
        } else if (doze_radio.isSelected()) {
            return "12+";
        } else if (quatorze_radio.isSelected()) {
            return "14+";
        } else if (dezesseis_radio.isSelected()) {
            return "16+";
        } else if (dezoito_radio.isSelected()) {
            return "18+";
        }
        return "Não selecionado";
    }

    private void criarFilme() {
        String nome = filme_input.getText();
        String descricao = descricao_input.getText();
        String classificacao = getClassificacao();
        Integer minutos = Integer.parseInt(duracao_text.getText());

        boolean sucesso;

        try {
            FilmeControl film = new FilmeControl();
            sucesso = film.cadastrarFilme(nome, descricao, classificacao, minutos, imagemBase64);
            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                voltar();
            } else {
                JOptionPane.showMessageDialog(null, "Erro no preenchimento de campos!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }

    }

    private void uploadImage() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(getParent());

        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                BufferedImage picture = ImageIO.read(file);

                ImageIcon imageIcon = new ImageIcon(picture);
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(165, 220, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);

                image_label.setIcon(imageIcon);
                image_action.setText("Remover imagem");

                imagemBase64 = converterImagemParaBase64(file);
            } catch (IOException ioe) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar a imagem.");
            }
        }
    }

    private String converterImagemParaBase64(File file) {
        try {
            FileInputStream fis = new FileInputStream(file);
            byte[] bytes = fis.readAllBytes();
            fis.close();
            return Base64.getEncoder().encodeToString(bytes);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    private void resetImage() {
        image_label.setIcon(null);
        image_action.setText("Subir imagem");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_botao;
    private javax.swing.JTextArea descricao_input;
    private javax.swing.JRadioButton dez_radio;
    private javax.swing.JRadioButton dezesseis_radio;
    private javax.swing.JRadioButton dezoito_radio;
    private javax.swing.JRadioButton doze_radio;
    private javax.swing.JFormattedTextField duracao_text;
    private javax.swing.JTextField filme_input;
    private javax.swing.ButtonGroup idade_grupo;
    private javax.swing.JButton image_action;
    private javax.swing.JLabel image_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton livre_radio;
    private javax.swing.JRadioButton quatorze_radio;
    private javax.swing.JButton voltar_botao;
    // End of variables declaration//GEN-END:variables
}
