package view;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import model.dao.DaoFactory;
import model.dao.IngressoDao;
import model.entities.Ingresso;
import model.entities.Sessao;

/**
 *
 * @author Scalco
 */
public class TelaEscolherAssento extends javax.swing.JFrame {

    private final Color defaultColor = new Color(255, 255, 255);
    private final Color selectedColor = new Color(153, 255, 153);
    private final Color ocupedColor = new Color(255, 102, 102);

    private static TelaEscolherAssento unicEscolherAssento;

    private ArrayList<String> assentosReservados = new ArrayList<>();
    private Sessao sessao;

    private TelaEscolherAssento() {
        initComponents();
    }

    public static TelaEscolherAssento geraEscolherAssento() {
        if (unicEscolherAssento == null) {
            unicEscolherAssento = new TelaEscolherAssento();
        }

        return unicEscolherAssento;
    }

    public void abrirTela(Sessao sessao) {
        this.sessao = sessao;
        renderizaTela();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_label = new javax.swing.JLabel();
        reservar_botao = new javax.swing.JButton();
        voltar_botao = new javax.swing.JButton();
        quantidade__static_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        quantidade_label = new javax.swing.JLabel();
        assentos_panel = new javax.swing.JPanel();
        filme_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolher Assento");

        title_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_label.setText("Escolha seu assento");

        reservar_botao.setText("Reservar");
        reservar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservar_botaoActionPerformed(evt);
            }
        });

        voltar_botao.setText("Voltar");
        voltar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_botaoActionPerformed(evt);
            }
        });

        quantidade__static_label.setText("Quantidade selecionada:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Livre");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Reservado");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ocupado");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(16, 16));
        jPanel1.setMinimumSize(new java.awt.Dimension(16, 16));
        jPanel1.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(16, 16));
        jPanel2.setMinimumSize(new java.awt.Dimension(16, 16));
        jPanel2.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setMaximumSize(new java.awt.Dimension(16, 16));
        jPanel3.setMinimumSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        quantidade_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quantidade_label.setText("0");

        filme_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        filme_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filme_label.setText("Filme");

        javax.swing.GroupLayout assentos_panelLayout = new javax.swing.GroupLayout(assentos_panel);
        assentos_panel.setLayout(assentos_panelLayout);
        assentos_panelLayout.setHorizontalGroup(
            assentos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filme_label, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        assentos_panelLayout.setVerticalGroup(
            assentos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assentos_panelLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(filme_label)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltar_botao)
                            .addComponent(title_label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantidade__static_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidade_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(assentos_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservar_botao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltar_botao, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidade__static_label)
                            .addComponent(quantidade_label))
                        .addGap(18, 18, 18)
                        .addComponent(assentos_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_botaoActionPerformed
        voltar();
    }//GEN-LAST:event_voltar_botaoActionPerformed

    private void reservar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservar_botaoActionPerformed
        reservar();
    }//GEN-LAST:event_reservar_botaoActionPerformed

    private List<Ingresso> pegarIngressosDaSessao() {
        IngressoDao ingressoDao = DaoFactory.createIngressoDao();
        return ingressoDao.findBySection(sessao.getId());
    }

    private void renderizaTela() {
        assentosReservados.clear();
        quantidade_label.setText("0");
        assentos_panel.removeAll();

        ArrayList<String> listaAssentosOcupados = new ArrayList<>();

        for (Ingresso ingresso : pegarIngressosDaSessao()) {
            listaAssentosOcupados.add(ingresso.getAssento());
        }

        int largura = sessao.getSala().getLargura();
        int profundidade = sessao.getSala().getProfundidade();

        int panelHeight = 350;
        int assentoW = 47;
        int assentoH = 30;
        int space = 5;
        int x = 0;
        int y = panelHeight - assentoH - 40;

        for (int letra = 0; letra < profundidade; letra++) {
            x = 0;
            for (int num = 1; num <= largura; num++) {
                String codigoAssento = String.valueOf((char) (letra + 65)) + Integer.toString(num);
                boolean estaOcupado = listaAssentosOcupados.contains(codigoAssento);
                javax.swing.JButton botao = new javax.swing.JButton();
                botao.setIconTextGap(0);
                botao.setFont(new java.awt.Font("Segoe UI", 0, 10));
                botao.setLabel(codigoAssento);
                botao.setMargin(new java.awt.Insets(3, 0, 3, 0));
                botao.setBounds(x, y, assentoW, assentoH);
                botao.setBackground(estaOcupado ? ocupedColor : defaultColor);

                botao.addActionListener((java.awt.event.ActionEvent evt) -> {
                    toogleReservarAssento(botao, codigoAssento);
                });

                assentos_panel.add(botao);

                x = x + assentoW + space;
            }
            y = y - assentoH - space;
        }

        filme_label.setBounds(0, panelHeight - 20, x - space, 20);
        assentos_panel.add(filme_label);

        assentos_panel.setPreferredSize(new Dimension(x - space, panelHeight));
        assentos_panel.revalidate();
        assentos_panel.repaint();
    }

    private void voltar() {
        dispose();
        TelaFilme.geraFilme().abrirTela(sessao.getFilme());
    }

    private void reservar() {
        dispose();
        assentosReservados.sort(null);
        TelaReservarAssentos.geraTelaReservarAssentos().abrirTela(sessao, assentosReservados);
    }

    private void toogleReservarAssento(javax.swing.JButton button, String code) {
        Color color = button.getBackground();

        if (color.equals(ocupedColor)) {
            return;
        }

        if (color.equals(defaultColor)) {
            button.setBackground(selectedColor);
            assentosReservados.add(code);
        } else {
            button.setBackground(defaultColor);
            assentosReservados.remove(code);
        }

        atualizaQuantidade();
    }

    private void atualizaQuantidade() {
        int quantidade = assentosReservados.size();
        quantidade_label.setText(Integer.toString(quantidade));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assentos_panel;
    private javax.swing.JLabel filme_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel quantidade__static_label;
    private javax.swing.JLabel quantidade_label;
    private javax.swing.JButton reservar_botao;
    private javax.swing.JLabel title_label;
    private javax.swing.JButton voltar_botao;
    // End of variables declaration//GEN-END:variables
}
