package view;

import java.util.Date;
import model.entities.Filme;
import model.entities.Sala;
import model.entities.Sessao;

/**
 *
 * @author Scalco
 */
public class TelaFilme extends javax.swing.JFrame {

    private static TelaFilme unicFilme;
    private Filme filme;

    private TelaFilme() {
        initComponents();
    }

    public static TelaFilme geraFilme() {
        if (unicFilme == null) {
            unicFilme = new TelaFilme();
        }

        return unicFilme;
    }

    public void abrirTela(Filme filme) {
        this.filme = filme;
        renderizaTela();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filme_img = new javax.swing.JPanel();
        filme_nome = new javax.swing.JLabel();
        voltar_botao = new javax.swing.JButton();
        data_botao_1 = new javax.swing.JButton();
        data_botao_2 = new javax.swing.JButton();
        data_botao_3 = new javax.swing.JButton();
        data_botao_4 = new javax.swing.JButton();
        data_botao_5 = new javax.swing.JButton();
        idade_text = new javax.swing.JLabel();
        lingua_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_text = new javax.swing.JTextArea();
        hora_botao_1 = new javax.swing.JButton();
        hora_botao_2 = new javax.swing.JButton();
        hora_botao_3 = new javax.swing.JButton();
        hora_botao_4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filme_img.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout filme_imgLayout = new javax.swing.GroupLayout(filme_img);
        filme_img.setLayout(filme_imgLayout);
        filme_imgLayout.setHorizontalGroup(
            filme_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        filme_imgLayout.setVerticalGroup(
            filme_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        filme_nome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filme_nome.setText("Homem Aranha - vamos para Casa? ");

        voltar_botao.setText("Voltar");
        voltar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_botaoActionPerformed(evt);
            }
        });

        data_botao_1.setText("12/01");

        data_botao_2.setText("13/01");

        data_botao_3.setText("14/01");

        data_botao_4.setText("15/01");

        data_botao_5.setText("16/01");

        idade_text.setText("12+");

        lingua_text.setText("Dublado");

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setBorder(null);

        descricao_text.setEditable(false);
        descricao_text.setColumns(20);
        descricao_text.setLineWrap(true);
        descricao_text.setRows(5);
        descricao_text.setText("Homem Aranha vai para casa, brincar com a Mary Jane, e nesse filme ele te convida para ir para a casa com ele, em um filme cheio de suspence, drama e muita comédia, você descobrirá tudo que o homem aranha fará com você, dentro da sua casa, você está preparado, para as traquinagens aranhas?");
        descricao_text.setWrapStyleWord(true);
        descricao_text.setAutoscrolls(false);
        descricao_text.setBorder(null);
        jScrollPane1.setViewportView(descricao_text);

        hora_botao_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora_botao_1.setText("13:45");
        hora_botao_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_botao_1ActionPerformed(evt);
            }
        });

        hora_botao_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora_botao_2.setText("17:45");
        hora_botao_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_botao_2ActionPerformed(evt);
            }
        });

        hora_botao_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora_botao_3.setText("19:45");
        hora_botao_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_botao_3ActionPerformed(evt);
            }
        });

        hora_botao_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora_botao_4.setText("22:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hora_botao_1)
                        .addGap(18, 18, 18)
                        .addComponent(hora_botao_2)
                        .addGap(18, 18, 18)
                        .addComponent(hora_botao_3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filme_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filme_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(idade_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(lingua_text, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(voltar_botao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(data_botao_1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_botao_2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_botao_3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_botao_4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_botao_5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hora_botao_4))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar_botao)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filme_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filme_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lingua_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idade_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_botao_1)
                    .addComponent(data_botao_2)
                    .addComponent(data_botao_3)
                    .addComponent(data_botao_4)
                    .addComponent(data_botao_5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hora_botao_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_botao_2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_botao_3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hora_botao_4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_botaoActionPerformed
        voltar();
    }//GEN-LAST:event_voltar_botaoActionPerformed

    private void hora_botao_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_botao_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_botao_2ActionPerformed

    private void hora_botao_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_botao_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_botao_3ActionPerformed

    private void hora_botao_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_botao_1ActionPerformed
        irParaAssento();
    }//GEN-LAST:event_hora_botao_1ActionPerformed

    private void renderizaTela() {
        filme_nome.setText(filme.getNome());
        idade_text.setText(filme.getClassificacao());
        descricao_text.setText(filme.getDescricao());
    }

    private void voltar() {
        dispose();
        TelaCatalogoDeFilmes.geraCatalogoDeFilmes().abrirTela();
    }

    private void irParaAssento() {
        Filme mockFilme = new Filme();
        Sala mockSala = new Sala();
        Sessao mockSessao = new Sessao(0, "dublado", new Date(), mockFilme, mockSala);
        
        
        dispose();
        TelaEscolherAssento.geraEscolherAssento().abrirTela(mockSessao);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton data_botao_1;
    private javax.swing.JButton data_botao_2;
    private javax.swing.JButton data_botao_3;
    private javax.swing.JButton data_botao_4;
    private javax.swing.JButton data_botao_5;
    private javax.swing.JTextArea descricao_text;
    private javax.swing.JPanel filme_img;
    private javax.swing.JLabel filme_nome;
    private javax.swing.JButton hora_botao_1;
    private javax.swing.JButton hora_botao_2;
    private javax.swing.JButton hora_botao_3;
    private javax.swing.JButton hora_botao_4;
    private javax.swing.JLabel idade_text;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lingua_text;
    private javax.swing.JButton voltar_botao;
    // End of variables declaration//GEN-END:variables
}
